name: Generate README.md
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: TIL Auto-Format README
      uses: cflynn07/github-action-til-autoformat-readme@1.1.0
